In [1]:
import tensorflow as tf 

In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
sent =[
    "I love Python.",
    "It is summer raining.",
    "She is not very smart.",
    "Dogs are cute.",
    "Books are funbut borring too.",
    "We play chess always.",
    "The sun sets is very beautiful here.",]


In [4]:
##  We need to define vocaburary size

voc_size =10000

In [5]:
## One Hot for Every word 
one_hot_repr = [one_hot(words,voc_size) for words in sent]
one_hot_repr

[[6900, 3120, 8243],
 [2544, 2895, 1449, 5337],
 [6249, 2895, 2867, 270, 2517],
 [4500, 4630, 6303],
 [7082, 4630, 2155, 5289, 5857],
 [4787, 7606, 7941, 7529],
 [2243, 6264, 4185, 2895, 270, 6678, 8440]]

## Word Emberding Representation

In [6]:
from tensorflow.keras.layers import Embedding

In [7]:
## We use Pad_sequences :-  if we See the upper given data then we realised that every sentences have different no. of words so  
##                          we have to make equal maximum numbers of word in a sentences so that they can change Text into vectors .
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np 

In [9]:
sent_length = 10  ## this help to make sentences make longer till 8 .
embedded_docs = pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length) ##  we use this to add zeros to make sentences long accoding to sent_length.... 
                                                                             ##  we can use padding= 'post' for adding zeros at the end.
print(embedded_docs)

[[   0    0    0    0    0    0    0 6900 3120 8243]
 [   0    0    0    0    0    0 2544 2895 1449 5337]
 [   0    0    0    0    0 6249 2895 2867  270 2517]
 [   0    0    0    0    0    0    0 4500 4630 6303]
 [   0    0    0    0    0 7082 4630 2155 5289 5857]
 [   0    0    0    0    0    0 4787 7606 7941 7529]
 [   0    0    0 2243 6264 4185 2895  270 6678 8440]]


In [11]:
## Feature representation :- Feature representation turns real things (like words, images, sounds) into numbers that a computer can understand and work with.
##                           we can use maximum of 300 dimention but here we don't need that much so will use 15.

dim = 15

In [12]:
model = Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [13]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [14]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step


array([[[ 0.01772788, -0.03866953, -0.02289791, ..., -0.00720584,
          0.01439459, -0.00052489],
        [ 0.01772788, -0.03866953, -0.02289791, ..., -0.00720584,
          0.01439459, -0.00052489],
        [ 0.01772788, -0.03866953, -0.02289791, ..., -0.00720584,
          0.01439459, -0.00052489],
        ...,
        [ 0.01884245,  0.00521728,  0.02759216, ...,  0.04098481,
         -0.03980803, -0.00839963],
        [ 0.02517165, -0.0325921 , -0.01690982, ..., -0.01997441,
         -0.0029166 , -0.0071965 ],
        [ 0.01469249,  0.03289444,  0.04622427, ...,  0.04187305,
          0.04548366,  0.02546835]],

       [[ 0.01772788, -0.03866953, -0.02289791, ..., -0.00720584,
          0.01439459, -0.00052489],
        [ 0.01772788, -0.03866953, -0.02289791, ..., -0.00720584,
          0.01439459, -0.00052489],
        [ 0.01772788, -0.03866953, -0.02289791, ..., -0.00720584,
          0.01439459, -0.00052489],
        ...,
        [-0.04004035, -0.02346932,  0.00852673, ...,  